node('maven') 
{
  stage ('buildDev')
  {
    openshiftBuild(buildConfig: 'visualiser', showBuildLogs: 'true')
  }
  
  stage ('deployDev')
  {
    openshiftDeploy(deploymentConfig: 'visualiser')
  }
  
  stage ('scaleUp')
  {
   openshiftScale(deploymentConfig: 'visualiser',replicaCount: '1')
  }
  
  stage ('smokeTest')
  {
    timeout(time: 1, unit: 'HOURS') { input id: 'AppProd', message: 'Smoke Test Completed?', ok: 'OK'}
  }
  
  stage ('scaleDown')
  {
    openshiftScale(deploymentConfig: 'visualiser', replicaCount: '0')
  }
  
}