apiVersion: v1
kind: Template
metadata:
  name: vertx-polling-polls
parameters:
  - name: GIT_REPO
    description: "Source code repository"
    required: true
    value: https://github.com/benemon/vertx-polling-polls
    
  - name: GIT_REF
    value: master
    description: "Source code tree"
    required: true
    
  - name: OPINIONBEE_API_KEY
    description: "Opinion Bee API Key"
    required: true

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: visualiser
    name: visualiser
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: visualiser:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status: {}
    
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: visualiser
    name: visualiser
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: visualiser:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:latest
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: aaeaf7a61c526332
      type: Generic
    - github:
        secret: 0d071f69cf43db6c
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status: {}
    
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    generation: 1
    labels:
      app: visualiser
    name: visualiser
  spec:
    replicas: 1
    selector:
      deploymentconfig: visualiser
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: visualiser
          deploymentconfig: visualiser
      spec:
        containers:
        - env:
          - name: OB_API_KEY
            value: ${OPINIONBEE_API_KEY}
          - name: JAVA_OPTIONS
            value: -Djava.net.preferIPv4Stack=true
          image: visualiser:latest
          imagePullPolicy: Always
          name: visualiser
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: "/api/health/liveness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreashold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/api/health/readiness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreashold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - visualiser
        from:
          kind: ImageStreamTag
          name: visualiser:latest
      type: ImageChange
    - type: ConfigChange
  status: {}
    
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: visualiser
    name: visualiser
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: visualiser
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: visualiser
    name: visualiser
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: visualiser
      weight: 100
    wildcardPolicy: None
  status: {}
